blank_issues_enabled: false
contact_links:
  - name: ğŸ˜ æŠ•ç¨¿æŒ‡å—
    url: https://github.com/jaywcjlove/reference/blob/main/CONTRIBUTING.md
    about: è¯·åœ¨åšå‡ºä»»ä½•è´¡çŒ®ä¹‹å‰é€šè¯»!
  - name: ğŸš€ éƒ¨ç½²é•œåƒç½‘ç«™
    url: https://github.com/jaywcjlove/reference/issues/102#issue-1451649637
    about: éƒ¨ç½²é•œåƒç½‘ç«™æ•™ç¨‹åœ¨è¿™é‡Œ!
  - name: ğŸª© æ¸…å•æ’ç‰ˆå¸ƒå±€è¯´æ˜
    url: https://ref.xszhome.cn/docs/quickreference.html
    about: éƒ¨ç½²é•œåƒç½‘ç«™æ•™ç¨‹åœ¨è¿™é‡Œ!
  - name: ğŸª© Markdown è¯­æ³•è¯´æ˜
    url: https://ref.xszhome.cn/docs/markdown.html
    about: éƒ¨ç½²é•œåƒç½‘ç«™æ•™ç¨‹åœ¨è¿™é‡Œ!